defaultMarkdownHandler: "goldmark"

goldmark:
  extensions:
    definitionList: true
    footnote: true
    linkify: true
    strikethrough: true
    table: true
    taskList: true
    typographer: true
  parser:
    autoHeadingID: true
    autoHeadingIDType: "github"
    attribute:
      block: true
      title: true
  renderer:
    hardWraps: false
    unsafe: false
    xhtml: false

highlight:
  style: "trac"
  lineNumbersInTable: true
  noClasses: false

tableOfContents:
  endLevel: 2
  ordered: false
  startLevel: 2
