[book]
authors = ["yujian"]
language = "zh"
multilingual = false
src = "content"
title = "linux笔记"

[rust]
edition = "2021"

[output.html]
mathjax-support = true
site-url = "/linux/"
git-repository-url = "https://github.com/yujian1018/yujian1018.github.io/tree/master/linux"
edit-url-template = "https://github.com/yujian1018/yujian1018.github.io/edit/master/linux/{path}"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
